name_request_both = "CON Hi, please enter your name and email address, separated by a space\n"
name_request = "CON Hi there, please enter your name (alphabets only)...\n" 
incorrect_name_request = "CON You seemed to have entered a wrong name. Try Again\n"
email_request = "CON Please enter your email address now.\n"
incorrect_email_request = "CON That's an incorrect email address. Try again...\n"
session_end = "END Thank you for your input. Our message is just arriving.\n"
incorrect_session_end = "END Too many attempts, try again later\n"