<?php

namespace ATChallenge;

use Illuminate\Database\Eloquent\Model;
use FreddieDfre\AfricasTalkingLaravel5\AfricasTalkingLaravel5Facade as SMSProvider;

class User extends Model
{
    protected $table = "users";

    protected $fillable = [
        "username", "email", "phone"
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($user){
            $message = "You have registered successfully!";
            SMSProvider::sendMessage($user->phone, $message);
        });
    }
}
